fix: unable to convert DeltaTableConnectionConfig to json schema (#566)
A bump to the pydantic library now requires typing for Secrets. As a
result, In its current form, running

```python
from unstructured_ingest.processes.connectors.delta_table import DeltaTableConnectionConfig
DeltaTableConnectionConfig(table_uri="").model_json_schema()
```

results in
```
    raise TypeError(
TypeError: Can't get secret type from Secret. Please use Secret[<type>], or subclass from Secret[<type>] instead.
```

In addition to the fix, this PR adds tests to iterate over all
connectors and validate that the json schema can be generated from them.